### PR TITLE
fixing typo in project and adding test on it

### PR DESCRIPTION
**Pull request by NickolasVashchenko**
Small typo in Project class

### CODE REVIEW

**Comment by NickolasVashchenko** [comment]
failing builds because of old rubies

**Comment by dorack** [comment]
Good catch on the typo. and i agree with the other will have to get this merged in.

**Comment by NickolasVashchenko** [comment]
Sorry, @dorack, I'm not sure I've got you right. You're saying that you need approval of somebody else to merge it, aren't you?

**Comment by dorack** [comment]
this should have been merged in ages ago... corrected now

**Comment by NickolasVashchenko** [comment]
Okay, np! :)

**Pull request merged**
